import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/providers/heroui_provider";
import { Delius, Funnel_Display } from 'next/font/google';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const delius = Delius({
  subsets: ['latin'],
  variable: '--font-delius',
  display: 'swap', 
  weight: '400', 
});

const funnel_display = Funnel_Display({
  subsets: ['latin'],
  variable: '--font-funnel-display',
  display: 'swap',
  weight: '400',
});




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" >
      <body className={`${delius.variable, funnel_display.variable} min-h-screen bg-gradient-to-t from-indigo-700 via-indigo-900 via-100% to-indigo-700 animate-gradient`}>
        <main>
          <Providers>  {/* Provider Hero UI */}
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
