import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/providers/heroui_provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" >
      <body className=" min-h-screen bg-gradient-to-t from-indigo-700 via-indigo-900 via-100% to-indigo-700 animate-gradient">
        <main>
          <Providers>  {/* Provider Hero UI */}
            {children}
          </Providers>
        </main>
      </body>
    </html>
  );
}
