import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/providers/heroui_provider";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" >
      <body>
        <Providers>  {/* Provider Hero UI */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
